<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Upload/Replace</title>

    {{-- 1. Bootstrap CSS Link --}}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    {{-- 2. Custom Styles (Cleaned up for Bootstrap integration) --}}
    <style>
        /* Styles for the side-by-side container - Using Bootstrap's d-flex now, but keeping this for specificity */
        .display-container {
            /* Bootstrap handles 'display: flex' and 'gap' */
            align-items: flex-start; /* Aligns items to the top (Flexbox property) */
        }

        /* Style for the QR code wrapper */
        .qr-code-wrapper {
            /* Replacing inline styles with Bootstrap classes where possible */
            border: 1px solid #ccc;
            /* Ensures the SVG itself is centered within its container if it's smaller */
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/gallery') }}">Photo Management Portal</a>

            <div class="d-flex">
                @auth
                    <span class="navbar-text text-white me-3">
                        Welcome, <strong>{{ Auth::user()->name ?? 'User' }}</strong>!
                    </span>
                    <form action="{{ route('logout') }}" method="POST" class="d-inline">
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm">
                            Logout
                        </button>
                    </form>
                @endauth

                @guest
                    {{-- Note: 'route('login')' and 'route('register')' must be defined in your routes --}}
                    <a href="{{ route('login') }}" class="btn btn-light btn-sm me-2">Login</a>
                    <a href="{{ route('register') }}" class="btn btn-outline-light btn-sm">Register</a>
                @endguest
            </div>
        </div>
    </nav>

    {{-- Main Content Container --}}
    <div class="container my-5">

        <h1 class="mb-4">{{ $photo ? 'Replace Existing Photo' : 'Upload New Photo' }}</h1>

        {{-- Success Message --}}
        @if (session('success'))
            {{-- Using Bootstrap alert class --}}
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif

        {{-- Error Messages --}}
        @if ($errors->any())
            {{-- Using Bootstrap alert class --}}
            <div class="alert alert-danger" role="alert">
                <ul class="mb-0">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if ($photo)
            <h2 class="mt-5 mb-3">Current Photo and QR Code:</h2>

            {{-- FLEXBOX CONTAINER for side-by-side layout --}}
            {{-- Using Bootstrap classes: d-flex (display: flex), gap-5 (gap: 3rem), mb-4 (margin-bottom) --}}
            <div class="display-container d-flex gap-5 mb-4">

                {{-- 1. IMAGE DISPLAY AREA --}}
                <div class="image-wrapper">
                    <h3 class="h5">Uploaded Image</h3>
                    {{-- Using Bootstrap class for image thumbnail/border --}}
                <img src="{{ asset($photo->file_path) }}"
                    alt="{{ $photo->original_name }}"
                    class="img-fluid border p-1"
                    style="max-width: 300px; height: auto;">
                    <p class="mt-2 text-muted">Original File Name: <strong>{{ $photo->original_name }}</strong></p>
                </div>

                {{-- 2. QR CODE DISPLAY AREA --}}
                @if ($qrCode)
                    {{-- Using Bootstrap class: p-3 (padding) --}}
                    <div class="qr-code-wrapper p-3">
                        <h3 class="h5">QR Code Link</h3>
                        {{-- Render the raw SVG generated by the QrCode package --}}
                        {!! $qrCode !!}
                        <p class="text-center text-muted mt-2 small">Scan to view the photo.</p>
                    </div>
                @endif
            </div>

            <hr class="my-4">
        @endif

        <h2 class="mt-4 mb-3">Photo Upload/Replacement</h2>

        {{-- File Upload Form --}}
        @if(isset($photo) && $photo)
            <form action="{{ route('photo.update', $photo) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
        @else
            <form action="{{ route('photo.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
        @endif

            {{-- Using Bootstrap form controls --}}
            <div class="mb-3">
                <label for="photo_file" class="form-label">Choose Photo:</label>
                <input type="file" name="photo_file" id="photo_file" class="form-control" required>
            </div>

            {{-- Using Bootstrap button class --}}
            <button type="submit" class="btn btn-primary">
                {{ $photo ? 'Replace Photo' : 'Upload Photo' }}
            </button>
        </form>
    </div>

    {{-- 3. Bootstrap JavaScript Bundle (Optional, but good practice) --}}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

</body>
</html>
